
package org.psoft.wishlist.torque;


import org.apache.torque.om.Persistent;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Tue Nov 09 23:21:02 PST 2004]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */
public  class Gift
    extends org.psoft.wishlist.torque.BaseGift
    implements Persistent
{

    public boolean getWasPurchased(){
        int value = getPurchased();
        return (value==1);
    }    
    
    public void setWasPurchased(boolean value){
        int results = value?1:0;
        setPurchased(results);
    }
}
