package org.psoft.wishlist.torque;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Tue Nov 09 23:21:02 PST 2004]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class GiftPeer
    extends org.psoft.wishlist.torque.BaseGiftPeer
{
}
