
package org.psoft.wishlist.torque;


import org.apache.torque.om.Persistent;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Nov 10 11:19:20 PST 2005]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */
public  class News
    extends org.psoft.wishlist.torque.BaseNews
    implements Persistent
{
}
