package org.psoft.wishlist.torque.map;

import org.apache.torque.Torque;
import org.apache.torque.TorqueException;
import org.apache.torque.map.DatabaseMap;
import org.apache.torque.map.MapBuilder;
import org.apache.torque.map.TableMap;

/**
  *  This class was autogenerated by Torque on:
  *
  * [Thu Nov 10 14:42:08 PST 2005]
  *
  */
public class GiftMapBuilder implements MapBuilder
{
    /**
     * The name of this class
     */
    public static final String CLASS_NAME =
        "org.psoft.wishlist.torque.map.GiftMapBuilder";


    /**
     * The database map.
     */
    private DatabaseMap dbMap = null;

    /**
     * Tells us if this DatabaseMapBuilder is built so that we
     * don't have to re-build it every time.
     *
     * @return true if this DatabaseMapBuilder is built
     */
    public boolean isBuilt()
    {
        return (dbMap != null);
    }

    /**
     * Gets the databasemap this map builder built.
     *
     * @return the databasemap
     */
    public DatabaseMap getDatabaseMap()
    {
        return this.dbMap;
    }

    /**
     * The doBuild() method builds the DatabaseMap
     *
     * @throws TorqueException
     */
    public void doBuild() throws TorqueException
    {
        dbMap = Torque.getDatabaseMap("wishlist");

        dbMap.addTable("GIFT");
        TableMap tMap = dbMap.getTable("GIFT");

        tMap.setPrimaryKeyMethod(TableMap.ID_BROKER);

        tMap.setPrimaryKeyMethodInfo(tMap.getName());

              tMap.addPrimaryKey("GIFT.GIFT_ID", new Integer(0));
                    tMap.addColumn("GIFT.GIFT", "");
                    tMap.addColumn("GIFT.DESCR", "");
                    tMap.addColumn("GIFT.IS_PURCHASED", new Integer(0));
                    tMap.addColumn("GIFT.PURCHASED_BY", "");
                    tMap.addColumn("GIFT.INTIALS", "");
                    tMap.addColumn("GIFT.IS_SECRET", new Integer(0));
          }
}
